#!/usr/bin/env bash

set -euo pipefail

YSYX_HOME=$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
SHELL_RC=${HOME}/.bashrc

# Keep a single managed environment block so this script is safe to rerun.
touch "${SHELL_RC}"
sed -i '/^# >>> YSYX environment >>>$/,/^# <<< YSYX environment <<<$/{d;}' "${SHELL_RC}"
{
  echo '# >>> YSYX environment >>>'
  printf 'export YSYX_HOME=%q\n' "${YSYX_HOME}"
  printf 'export MEMU_HOME=%q\n' "${YSYX_HOME}/memu"
  printf 'export AM_HOME=%q\n' "${YSYX_HOME}/abstract-machine"
  printf 'export AM_TEST_HOME=%q\n' "${YSYX_HOME}/am-kernels"
  printf 'export NVBOARD_HOME=%q\n' "${YSYX_HOME}/thirdpartys/nvboard"
  echo '# <<< YSYX environment <<<'
} >> "${SHELL_RC}"

export YSYX_HOME
export MEMU_HOME="${YSYX_HOME}/memu"
export AM_HOME="${YSYX_HOME}/abstract-machine"
export AM_TEST_HOME="${YSYX_HOME}/am-kernels"
export NVBOARD_HOME="${YSYX_HOME}/thirdpartys/nvboard"

git -C "${YSYX_HOME}" submodule update --init --recursive --depth 1

RT_THREAD_HOME=${YSYX_HOME}/thirdpartys/rt-thread-am
RT_THREAD_PATCH=${YSYX_HOME}/misc/patches/rt-thread-am.patch
if git -C "${RT_THREAD_HOME}" apply --unidiff-zero --check "${RT_THREAD_PATCH}"; then
  git -C "${RT_THREAD_HOME}" apply --unidiff-zero "${RT_THREAD_PATCH}"
elif git -C "${RT_THREAD_HOME}" apply --unidiff-zero --reverse --check "${RT_THREAD_PATCH}"; then
  echo 'rt-thread-am patch already applied'
else
  echo "Failed to apply ${RT_THREAD_PATCH}" >&2
  exit 1
fi

# files.mk is generated by SCons and contains absolute paths. Regenerate it
# after a clone or whenever the repository has moved.
RT_THREAD_BSP=${RT_THREAD_HOME}/bsp/abstract-machine
RT_THREAD_FILES=${RT_THREAD_BSP}/files.mk
if [[ ! -f "${RT_THREAD_FILES}" ]] || ! grep -Fq "${RT_THREAD_HOME}/" "${RT_THREAD_FILES}"; then
  (
    cd "${RT_THREAD_BSP}"
    scons -c
    SCONS_OUTPUT=$(scons --verbose -n)
    printf '%s\n' "${SCONS_OUTPUT}" \
      | grep -o '[^ ]*\.c$' \
      | awk '{print "SRCS += " $1}' > files.mk
    printf '%s\n' "${SCONS_OUTPUT}" \
      | grep 'gcc ' \
      | head -n 1 \
      | grep -o ' -I[^ ]*' \
      | awk '{print "CFLAGS += " $1}' >> files.mk
  )
fi

echo "YSYX environment configured for ${YSYX_HOME}"
